package com.homefin.common.error;

// Lombok's @Slf4j annotation lives here; SLF4J is Java's standard logging facade (like "pino"/"winston").
import lombok.extern.slf4j.Slf4j;
// MDC = "Mapped Diagnostic Context": per-thread key/values attached to log lines
// (similar to AsyncLocalStorage-based request context in Node).
import org.slf4j.MDC;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

// java.* imports are the JDK standard library (like Node built-ins "node:url", etc.).
import java.net.URI;
import java.util.List;
import java.util.Map;

/**
 * Centralised error handling -> RFC 9457 "Problem Details" JSON for every error.
 * The Express equivalent is a final `app.use((err, req, res, next) => ...)` middleware.
 * NestJS equivalent: a global {@code @Catch()} exception filter.
 *
 * Extending ResponseEntityExceptionHandler gives consistent ProblemDetail bodies for all
 * built-in Spring MVC exceptions (400 bad JSON, 405, 415, validation...).
 *
 * <p>Who calls this? Spring MVC. When any controller (or code it calls) throws, the framework
 * looks for the most specific {@code @ExceptionHandler} method matching the exception type and
 * uses its return value as the HTTP response body. This class is registered in every servlet
 * service automatically via {@code CommonWebAutoConfiguration}.
 */
// @Slf4j (Lombok, compile time): generates
//   private static final org.slf4j.Logger log = LoggerFactory.getLogger(GlobalExceptionHandler.class);
// which is why "log" can be used below without being declared.
@Slf4j
// @RestControllerAdvice (Spring, runtime): marks this as a global "advice" for all controllers.
// Its @ExceptionHandler methods apply app-wide, and return values are serialized to JSON.
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

    // static = belongs to the class, not to an instance (one shared value, like a module-level const).
    // "static final" + UPPER_CASE name = the Java idiom for a constant.
    private static final String PROBLEM_BASE = "https://homefin.example/problems/";

    // @ExceptionHandler(X.class) (Spring, runtime): "call this method when an X (or subclass) is thrown".
    // ApiException.class is a reference to the class object itself (a runtime type token).
    @ExceptionHandler(ApiException.class)
    public ProblemDetail handleApiException(ApiException ex) {
        // getStatus()/getCode() were generated by Lombok's @Getter on ApiException.
        if (ex.getStatus().is5xxServerError()) {
            // {} are SLF4J placeholders filled by the following args; a trailing exception arg
            // is logged with its stack trace.
            log.error("Request failed: {}", ex.getMessage(), ex);
        } else {
            log.info("Request rejected: {} ({})", ex.getMessage(), ex.getCode());
        }
        return problem(ex.getStatus(), ex.getCode(), ex.getMessage());
    }

    // Thrown by JPA when an entity's @Version no longer matches the DB row (someone else saved first).
    @ExceptionHandler(OptimisticLockingFailureException.class)
    public ProblemDetail handleOptimisticLock(OptimisticLockingFailureException ex) {
        return problem(HttpStatus.CONFLICT, "concurrent-modification",
                "The resource was modified by another request. Reload and retry.");
    }

    // Thrown by Spring Security when e.g. a @PreAuthorize check fails -> 403.
    @ExceptionHandler(AccessDeniedException.class)
    public ProblemDetail handleAccessDenied(AccessDeniedException ex) {
        return problem(HttpStatus.FORBIDDEN, "forbidden", "You are not allowed to perform this action");
    }

    /** Last line of defence: never leak stack traces / internals to clients. */
    // Exception is the parent of (almost) everything, so this catches whatever the more specific
    // handlers above did not. Spring always picks the most specific matching handler.
    @ExceptionHandler(Exception.class)
    public ProblemDetail handleUnexpected(Exception ex) {
        log.error("Unexpected error", ex);
        return problem(HttpStatus.INTERNAL_SERVER_ERROR, "internal-error", "An unexpected error occurred");
    }

    /** Bean Validation failures on {@code @Valid @RequestBody} -> 400 with per-field errors. */
    // @Override (compile time check): "this method replaces one from the parent class". If the
    // signature doesn't match a parent method, compilation fails - like TS's "override" keyword.
    // The parent ResponseEntityExceptionHandler calls this hook when @Valid validation fails.
    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,
                                                                  HttpHeaders headers,
                                                                  HttpStatusCode status,
                                                                  WebRequest request) {
        // Generics: List<Map<String, String>> is a list of string-to-string maps,
        // the same as TS Array<Record<string, string>>.
        // .stream().map(...).toList() is Java's version of array.map(...): a Stream is a lazy
        // pipeline over a collection, and toList() collects the results into a new (immutable) List.
        // "fe -> Map.of(...)" is a lambda, i.e. the arrow function (fe) => ({ ... }).
        // Map.of(k1, v1, k2, v2) builds an immutable map, like { field: ..., message: ... }.
        List<Map<String, String>> errors = ex.getBindingResult().getFieldErrors().stream()
                .map(fe -> Map.of(
                        "field", fe.getField(),
                        "message", String.valueOf(fe.getDefaultMessage())))
                .toList();
        // "Global" errors come from class-level constraints (e.g. a custom cross-field check).
        List<String> globalErrors = ex.getBindingResult().getGlobalErrors().stream()
                .map(ge -> String.valueOf(ge.getDefaultMessage()))
                .toList();

        ProblemDetail body = problem(HttpStatus.BAD_REQUEST, "validation-failed", "Request validation failed");
        // setProperty adds extra JSON fields next to the standard type/title/status/detail fields.
        body.setProperty("errors", errors);
        if (!globalErrors.isEmpty()) {
            body.setProperty("globalErrors", globalErrors);
        }
        // ResponseEntity = status + headers + body; like res.status(400).json(body).
        return ResponseEntity.badRequest().body(body);
    }

    // A private static helper: no access to instance fields, callable only inside this class.
    private static ProblemDetail problem(HttpStatusCode status, String code, String detail) {
        ProblemDetail pd = ProblemDetail.forStatusAndDetail(status, detail);
        pd.setType(URI.create(PROBLEM_BASE + code));
        pd.setTitle(code);
        // Micrometer Tracing puts traceId in the MDC -> lets support correlate a client error with logs.
        String traceId = MDC.get("traceId");
        // Any object reference may be null in Java; there's no "undefined" and no strict null checks.
        if (traceId != null) {
            pd.setProperty("traceId", traceId);
        }
        return pd;
    }
}
