package com.homefin.customer.kyc;

// java.time.LocalDate = a calendar date without time or time zone (e.g. 1990-05-17). Serialized as "1990-05-17".
import java.time.LocalDate;

/**
 * Shape of the 3rd-party provider's API - kept separate from our own DTOs (anti-corruption layer).
 *
 * <p>This is the JSON body {@code KycClient} POSTs to the provider. Keeping the provider's shape in its own type
 * means a provider API change only touches the kyc package, not our REST API or entity.
 *
 * <p>A {@code record} is an immutable data class: the header {@code (String firstName, ...)} declares private final
 * fields plus a constructor, accessor methods {@code firstName()} (no "get" prefix), {@code equals},
 * {@code hashCode} and {@code toString}, all generated by the compiler. Think {@code Readonly<{ firstName: string;
 * ... }>} but as a real class. Jackson serializes it to JSON using the component names.
 */
public record KycVerificationRequest(String firstName, String lastName, LocalDate dateOfBirth, String nationalId) {

    // @Override (compile time): asserts this method replaces one inherited from a parent type (here the
    // record's generated toString). The compiler errors if nothing is being overridden, e.g. after a typo.
    // Overridden on purpose: the default toString would print dateOfBirth and nationalId (PII) into logs.
    @Override
    public String toString() {
        // "text %s".formatted(x) is String formatting, like util.format('text %s', x) or a template literal.
        return "KycVerificationRequest[firstName=%s]".formatted(firstName);
    }
}
