package com.homefin.customer.customer;

import com.homefin.common.error.BusinessRuleException;
import com.homefin.common.persistence.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * "Rich" entity: state changes go through intention-revealing methods (updateProfile, markKycResult)
 * instead of public setters, so invariants live in one place.
 *
 * <p>A JPA entity = one row of the {@code customers} table, like a TypeORM {@code @Entity()} class or a Prisma
 * model. Hibernate (the JPA implementation) creates instances when loading rows and tracks changes to them.
 *
 * <p>Annotations on the class:
 * <ul>
 *   <li>{@code @Entity} (runtime, JPA): Hibernate manages this class as a persistent type.</li>
 *   <li>{@code @Table(name = "customers")} (runtime): the table it maps to (the schema itself comes from Flyway).</li>
 *   <li>{@code @Getter} (Lombok, compile time): generates {@code getUserId()}, {@code getEmail()}... for every field.
 *       Deliberately no {@code @Setter}: fields change only through the business methods below.</li>
 *   <li>{@code @NoArgsConstructor(access = PROTECTED)} (Lombok, compile time): generates an empty constructor.
 *       JPA requires one to instantiate entities via reflection; "protected" hides it from normal code so everyone
 *       else must use the {@code register(...)} factory method.</li>
 * </ul>
 *
 * <p>{@code extends BaseEntity}: inherits the shared columns id (UUID generated by Hibernate), createdAt/updatedAt
 * (filled by JPA auditing) and version (optimistic locking) from common-lib, like extending an abstract base
 * entity class in TypeORM.
 */
@Entity
@Table(name = "customers")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Customer extends BaseEntity {

    /** The auth-service user id ("sub" claim). Services share IDs, never database tables. */
    // @Column (runtime): maps the field to a column. Without it JPA would still map the field, using default naming.
    // updatable = false: Hibernate never includes it in UPDATE statements. nullable/unique/length describe the
    // schema (used for validation with ddl-auto=validate); they do not add runtime checks in Java.
    @Column(name = "user_id", nullable = false, unique = true, updatable = false)
    private UUID userId;

    @Column(nullable = false)
    private String email;

    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    @Column(name = "phone_number", length = 20)
    private String phoneNumber;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    /** Sensitive PII: in production encrypt at rest (column-level encryption / KMS). */
    @Column(name = "national_id", length = 20)
    private String nationalId;

    // @Enumerated(EnumType.STRING) (runtime): store the enum's NAME ("PENDING"). The default (ORDINAL) stores its
    // position 0/1/2, which silently corrupts data if someone reorders the constants.
    // "= KycStatus.PENDING" is a field initializer: every new Customer starts as PENDING.
    @Enumerated(EnumType.STRING)
    @Column(name = "kyc_status", nullable = false, length = 20)
    private KycStatus kycStatus = KycStatus.PENDING;

    @Column(name = "kyc_reference", length = 64)
    private String kycReference;

    @Column(name = "kyc_checked_at")
    private Instant kycCheckedAt;

    // Static factory method: the only public way to create a new Customer (the constructor is protected).
    // "static" = called on the class: Customer.register(...), no instance needed. A method inside the class may
    // assign private fields of any instance of the same class (c.userId = ...).
    public static Customer register(UUID userId, String email, String firstName, String lastName) {
        Customer c = new Customer();
        c.userId = userId;
        c.email = email;
        c.firstName = firstName;
        c.lastName = lastName;
        return c;
    }

    // Business method with an invariant: once verified, the national ID is frozen.
    // Hibernate notices the field changes itself (dirty checking) and issues the UPDATE when the transaction commits.
    public void updateProfile(String firstName, String lastName, String phoneNumber,
                              LocalDate dateOfBirth, String nationalId) {
        // "==" on enums compares identity, which is correct for enum constants. For Strings use .equals():
        // "==" on objects compares references, not content (unlike JS === on strings).
        if (kycStatus == KycStatus.VERIFIED && !nationalId.equals(this.nationalId)) {
            // "throw new ..." works like JS. BusinessRuleException is unchecked, so no "throws" clause is needed;
            // common-lib's GlobalExceptionHandler turns it into an HTTP 422 problem response.
            throw new BusinessRuleException("national-id-locked", "National ID cannot change after KYC verification");
        }
        // "this.firstName" = the field; plain "firstName" = the parameter that shadows it.
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.dateOfBirth = dateOfBirth;
        this.nationalId = nationalId;
    }

    // Boolean getters use the "is" prefix by convention (JavaBeans), so Jackson/EL would see "profileComplete".
    public boolean isProfileComplete() {
        return dateOfBirth != null && nationalId != null && phoneNumber != null;
    }

    public void markKycResult(boolean approved, String reference, Instant checkedAt) {
        // Ternary operator "cond ? a : b", same as JS.
        this.kycStatus = approved ? KycStatus.VERIFIED : KycStatus.REJECTED;
        this.kycReference = reference;
        this.kycCheckedAt = checkedAt;
    }
}
