package com.homefin.customer.customer;

import com.homefin.common.error.BusinessRuleException;
import com.homefin.customer.kyc.KycClient;
import com.homefin.customer.kyc.KycVerificationResponse;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

// Static imports of the assertion/mocking helper functions (so we can write given(...) instead of
// BDDMockito.given(...)). BDD style: given(...) = arrange a stub, then(...).should() = verify an interaction.
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.then;
import static org.mockito.Mockito.never;

/**
 * Pure unit test with Mockito (like jest.mock). No Spring, no DB.
 *
 * <ul>
 *   <li>{@code @ExtendWith(MockitoExtension.class)} (runtime, JUnit): plug Mockito into the test lifecycle so the
 *       annotations below are processed before each test (and unused stubs are reported as errors).</li>
 *   <li>{@code @Mock}: create a fake implementation whose methods return empty defaults (null, false, 0,
 *       empty Optional) until stubbed, like {@code jest.fn()} / {@code jest.mock('./repo')}.</li>
 *   <li>{@code @InjectMocks}: create a real {@code CustomerService} and pass the mocks into its constructor,
 *       i.e. {@code new CustomerService(customers, kycClient)} done for you.</li>
 * </ul>
 */
@ExtendWith(MockitoExtension.class)
class CustomerServiceTest {

    @Mock
    CustomerRepository customers;

    @Mock
    KycClient kycClient;

    @InjectMocks
    CustomerService service;

    // @Test (runtime, JUnit): one test case, like it('kyc requires complete profile', ...).
    @Test
    void kycRequiresCompleteProfile() {
        UUID userId = UUID.randomUUID();
        // Stub: when findByUserId(userId) is called, return this Optional.
        // Like customers.findByUserId.mockReturnValue(...). Optional.of(x) = a non-empty Optional.
        given(customers.findByUserId(userId))
                .willReturn(Optional.of(Customer.register(userId, "a@b.com", "A", "B")));

        // Like expect(() => service.verifyKyc(userId)).toThrow(BusinessRuleException) plus a message check.
        assertThatThrownBy(() -> service.verifyKyc(userId))
                .isInstanceOf(BusinessRuleException.class)
                .hasMessageContaining("Complete");
        // Verify the provider was never called: expect(kycClient.verify).not.toHaveBeenCalled().
        // any()/anyString() are argument matchers, like expect.anything().
        then(kycClient).should(never()).verify(any(), anyString());
    }

    @Test
    void approvedKycMarksCustomerVerified() {
        UUID userId = UUID.randomUUID();
        Customer customer = Customer.register(userId, "a@b.com", "A", "B");
        // The id is normally generated by Hibernate on save and has no setter; set the private field via
        // reflection for this unit test.
        ReflectionTestUtils.setField(customer, "id", UUID.randomUUID());
        customer.updateProfile("A", "B", "+971501234567", LocalDate.of(1990, 1, 1), "784-1990-1234567-1");

        given(customers.findByUserId(userId)).willReturn(Optional.of(customer));
        given(customers.findById(customer.getId())).willReturn(Optional.of(customer));
        // willAnswer: compute the return value from the call, like mockImplementation(c => c).
        // inv.getArgument(0) returns the first argument passed to save().
        given(customers.save(any(Customer.class))).willAnswer(inv -> inv.getArgument(0));
        given(kycClient.verify(any(), anyString()))
                .willReturn(new KycVerificationResponse("KYC-123", "APPROVED", 91));

        Customer result = service.verifyKyc(userId);

        assertThat(result.getKycStatus()).isEqualTo(KycStatus.VERIFIED);
        assertThat(result.getKycReference()).isEqualTo("KYC-123");
    }
}
